### PR TITLE
Fixes for adding LHD events

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by lachlanjc** [comment]
Lmk if you want me to look at this, otherwise will leave it to you

**Comment by maxwofford** [comment]
Thanks @lachlanjc, will let you know once it's ready for review

**Comment by maxwofford** [comment]
@lachlanjc ok, this is ready for review

**Comment by maxwofford** [comment]
Merging for the sake of time, will review comments left here later though @lachlanjc

**Pull request merged**
